/* Allegro datafile object indexes, produced by grabber v3.9.40 (WIP), djgpp */
/* Datafile: c:\MYGAMES\EXAMPLE\ISO\DATA.DAT */
/* Date: Tue Dec  4 09:28:37 2001 */
/* Do not hand edit! */

#define BACK                             0        /* BMP  */
#define BLACK                            1        /* BMP  */
#define BUTTON01                         2        /* BMP  */
#define BUTTON02                         3        /* BMP  */
#define BUTTON03                         4        /* BMP  */
#define BUTTON04                         5        /* BMP  */
#define BUTTON05                         6        /* BMP  */
#define BUTTON06                         7        /* BMP  */
#define BUTTON07                         8        /* BMP  */
#define BUTTON08                         9        /* BMP  */
#define BUTTON09                         10       /* BMP  */
#define BUTTON10                         11       /* BMP  */
#define BUTTON11                         12       /* BMP  */
#define BUTTON12                         13       /* BMP  */
#define CHARLIE                          14       /* BMP  */
#define COLOR_HELPER                     15       /* BMP  */
#define FLOOR000                         16       /* BMP  */
#define FLOOR001                         17       /* BMP  */
#define FLOOR002                         18       /* BMP  */
#define FLOOR003                         19       /* BMP  */
#define FLOOR004                         20       /* BMP  */
#define FLOOR005                         21       /* BMP  */
#define FLOOR006                         22       /* BMP  */
#define FLOOR007                         23       /* BMP  */
#define FLOOR008                         24       /* BMP  */
#define FLOOR009                         25       /* BMP  */
#define FLOOR010                         26       /* BMP  */
#define FLOOR011                         27       /* BMP  */
#define FLOOR012                         28       /* BMP  */
#define FLOOR013                         29       /* BMP  */
#define FLOOR014                         30       /* BMP  */
#define FLOOR015                         31       /* BMP  */
#define FLOOR016                         32       /* BMP  */
#define FLOOR017                         33       /* BMP  */
#define FLOOR018                         34       /* BMP  */
#define FLOOR019                         35       /* BMP  */
#define FLOOR020                         36       /* BMP  */
#define FLOOR021                         37       /* BMP  */
#define FLOOR022                         38       /* BMP  */
#define FLOOR023                         39       /* BMP  */
#define FLOOR024                         40       /* BMP  */
#define FLOOR025                         41       /* BMP  */
#define FLOOR026                         42       /* BMP  */
#define FLOOR027                         43       /* BMP  */
#define FLOOR028                         44       /* BMP  */
#define FLOOR029                         45       /* BMP  */
#define FLOOR030                         46       /* BMP  */
#define FLOOR031                         47       /* BMP  */
#define FLOOR032                         48       /* BMP  */
#define FLOOR033                         49       /* BMP  */
#define FLOOR034                         50       /* BMP  */
#define FLOOR035                         51       /* BMP  */
#define FLOOR036                         52       /* BMP  */
#define FLOOR037                         53       /* BMP  */
#define FLOOR038                         54       /* BMP  */
#define FLOOR039                         55       /* BMP  */
#define FLOOR040                         56       /* BMP  */
#define FLOOR041                         57       /* BMP  */
#define FLOOR042                         58       /* BMP  */
#define FLOORZZZ                         59       /* BMP  */
#define FONT01                           60       /* FONT */
#define FONT02                           61       /* FONT */
#define GRID_MOUSE                       62       /* BMP  */
#define HALO                             63       /* BMP  */
#define MOUSE01                          64       /* BMP  */
#define MOUSE02                          65       /* BMP  */
#define MOUSE03                          66       /* BMP  */
#define MY_PAL                           67       /* PAL  */
#define PAPER1                           68       /* BMP  */
#define PAPER2                           69       /* BMP  */
#define ROOF000                          70       /* BMP  */
#define ROOF001                          71       /* BMP  */
#define ROOF002                          72       /* BMP  */
#define ROOF003                          73       /* BMP  */
#define ROOF004                          74       /* BMP  */
#define ROOF005                          75       /* BMP  */
#define ROOF006                          76       /* BMP  */
#define ROOF007                          77       /* BMP  */
#define ROOF008                          78       /* BMP  */
#define ROOF009                          79       /* BMP  */
#define ROOF010                          80       /* BMP  */
#define ROOF011                          81       /* BMP  */
#define ROOF012                          82       /* BMP  */
#define ROOF013                          83       /* BMP  */
#define ROOF014                          84       /* BMP  */
#define ROOF015                          85       /* BMP  */
#define ROOF016                          86       /* BMP  */
#define ROOF017                          87       /* BMP  */
#define ROOFZZZ                          88       /* BMP  */
#define SCROLL                           89       /* BMP  */
#define SHADE                            90       /* BMP  */
#define SPOT                             91       /* BMP  */
#define TILE000                          92       /* BMP  */
#define TILE001                          93       /* BMP  */
#define TILE002                          94       /* BMP  */
#define TILE003                          95       /* BMP  */
#define TILE004                          96       /* BMP  */
#define TILE005                          97       /* BMP  */
#define TILE006                          98       /* BMP  */
#define TILE007                          99       /* BMP  */
#define TILE008                          100      /* BMP  */
#define TILE009                          101      /* BMP  */
#define TILE010                          102      /* BMP  */
#define TILE011                          103      /* BMP  */
#define TILE012                          104      /* BMP  */
#define TILE013                          105      /* BMP  */
#define TILE014                          106      /* BMP  */
#define TILE015                          107      /* BMP  */
#define TILE016                          108      /* BMP  */
#define TILE017                          109      /* BMP  */
#define TILE018                          110      /* BMP  */
#define TILE019                          111      /* BMP  */
#define TILE020                          112      /* BMP  */
#define TILE021                          113      /* BMP  */
#define TILE022                          114      /* BMP  */
#define TILE023                          115      /* BMP  */
#define TILE024                          116      /* BMP  */
#define TILE025                          117      /* BMP  */
#define TILE026                          118      /* BMP  */
#define TILE027                          119      /* BMP  */
#define TILE028                          120      /* BMP  */
#define TILE029                          121      /* BMP  */
#define TILE030                          122      /* BMP  */
#define TILE031                          123      /* BMP  */
#define TILE033                          124      /* BMP  */
#define TILEZZZ                          125      /* BMP  */

